env:
  commonjs: true
  es6: true
  node: true
extends: google
parserOptions:
  ecmaVersion: 2018
rules:
  max-len:
    - error
    - code: 120
  require-jsdoc:
    - off
  indent: off
  no-tabs: off
  new-cap: off
  no-trailing-spaces: off
  comma-dangle: off
